# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: frekele/java:jdk8u152

pipelines:
  default:
    - step:
        caches:
          - gradle
        script: # Modify the commands below to build your repository.
          # You must commit the Gradle wrapper to your repository
          # https://docs.gradle.org/current/userguide/gradle_wrapper.html
          
          - bash ./gradlew aCiVersion
          - bash ./gradlew build
          - bash ./gradlew copylib
          - bash ./gradlew izPackCreateInstaller
          - bash ./gradlew bzipCi
          

          #- curl -X POST --user ${BB_AUTH_STRING} "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"h2.bat"
          - curl -X POST --user "${BITBUCKET_REPO_OWNER}:${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads/" --form files=@"h2.bat"

          #- bash ./gradlew createsh
          #- bash ./move.sh ${BB_AUTH_STRING} ${BITBUCKET_REPO_OWNER} ${BITBUCKET_REPO_SLUG}
          #- curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"ci/*.*"
