version: "2"
services: 
  mysql:
    image: mysql:5.5
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=qsystem"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/db
      - ../mysql:/var/lib/mysql
