version: "2"
services: 
  mysql:
    image: mysql:5.5
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=qsystem"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/db
      - ../mysql:/var/lib/mysql
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami
  jasperreports:
    image: bitnami/jasperreports:latest
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
      - mysql
    ports:
      - '8000:8080'
      - '443:8443'
    volumes:
      - jasperreports_data:/bitnami

volumes:
  mariadb_data:
    driver: local
  jasperreports_data:
    driver: local

